spring:
  pid:
    file: ./pid/apppid
  datasource:
    druid:
     driver-class-name: com.mysql.jdbc.Driver
     password: root
     username: root
     url: jdbc:mysql://localhost:3306/ssmbuild?characterEncoding=UTF-8
          # 连接池配置
          # 配置初始化大小、最小、最大
     initial-size: 5
     max-active: 20
     min-idle: 5
          # 获取连接等待超时时间
     max-wait: 60000
     pool-prepared-statements: true
          #
     validation-query: SELECT 1
     test-on-borrow: false
     test-on-return: false
     test-while-idle: true
          # 间隔多久进行一次检测，检测需要关闭的空闲连接
     time-between-eviction-runs-millis: 60000
          # 一个连接在连接池中最小的生存时间
     min-evictable-idle-time-millis: 300000
     max-pool-prepared-statement-per-connection-size: 20
          # 合并多个DruidDataSource的监控数据
     use-global-data-source-stat: true
     filters: stat

          # 监控配置
          # Druid WebStatFilter配置
     web-stat-filter:
      enabled: true
      url-pattern: /*
      exclusions: /druid/*,*.gif,*.png,*.jpg,*.html,*.js,*.css,*.ico
          # Druid StatViewServlet配置
     stat-view-servlet:
      enabled: true
      url-pattern: /druid/*
           # 登录监控界面的用户名以及密码，登录url为localhost:8080/druid
      login-username: admin
      login-password: admin
      allow:
      deny:
     filter:
      stat:
        slow-sql-millis: 200
        log-slow-sql: true
  jpa:
    show-sql: true
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.tracy.ssm.springboot.pojo